DROP TABLE PRODUCT;

CREATE TABLE PRODUCT(
    PRODUCT_ID NUMBER(10),
    PRODUCT_NAME VARCHAR(20),
    PRICE NUMBER(30),
    QUANTITY NUMBER (30)
);


INSERT INTO PRODUCT
(PRODUCT_ID ,PRODUCT_NAME,PRICE,QUANTITY)
VALUES(001,'RICE',60,1000);

INSERT INTO PRODUCT
(PRODUCT_ID ,PRODUCT_NAME,PRICE,QUANTITY)
VALUES(002,'oil',120,500);

INSERT INTO PRODUCT
(PRODUCT_ID ,PRODUCT_NAME,PRICE,QUANTITY)
VALUES(003,'suger',75,500);

INSERT INTO PRODUCT
(PRODUCT_ID ,PRODUCT_NAME,PRICE,QUANTITY)
VALUES(004,'flour',35,80);

SELECT * FROM PRODUCT;




UPDATE PRODUCT 
SET QUANTITY = (SELECT QUANTITY FROM PRODUCT WHERE PRODUCT_NAME = 'suger')-2
WHERE PRODUCT_ID = 003;

SELECT * FROM PRODUCT ;
